amosproj/amos2023ws03-gui-frame-diff

.githooks/pre-commit
README.md

This tries to tackle #10  (this should link the PR to the issue).
I suggest we all use our favourite IDE and on-save code formatter.
To ensure that the coding style is consistent I build a pre-commit hook that uses the tool `ktlint`.
Guidance for activation of the hook is in the README file.

Adding coding conventions.

---

VideoGenerator/example/app/src/main/java/de/guiframediff/videogeneratorexample/MainActivity.kt
VideoGenerator/example/app/src/main/res/layout/main.xml
VideoGenerator/library/src/main/kotlin/AbstractVideoGenerator.kt
VideoGenerator/library/src/main/kotlin/VideoGeneratorImpl.kt

feat(lib1): input

---

VideoGenerator/README.md
VideoGenerator/example/app/.gitignore
VideoGenerator/example/app/build.gradle.kts

This will download the zipped pngs into the testAndroid res directory with a gradle task and then unzip them

-added gradle task to download test data from ftp

---

VideoGenerator/example/app/.gitignore
VideoGenerator/example/app/build.gradle.kts
VideoGenerator/example/app/src/androidTest/AndroidManifest.xml
VideoGenerator/example/app/src/androidTest/java/de/guiframediff/videogeneratorexample/VideoGeneratorFileSystemTest.kt
VideoGenerator/example/app/src/debug/AndroidManifest.xml
VideoGenerator/example/app/src/main/AndroidManifest.xml
VideoGenerator/example/app/src/main/java/de/guiframediff/videogeneratorexample/MainActivity.kt
VideoGenerator/example/app/src/test/java/de/guiframediff/videogeneratorexample/VideoGeneratorFileSystemTest.kt
VideoGenerator/library/src/main/kotlin/VideoGeneratorImpl.kt

should close #55  but blocked by #58 to ensure tests actually run

added tests for video generation from system files

---

DifferenceGenerator/build.gradle.kts
DifferenceGenerator/src/main/kotlin/Main.kt
DifferenceGenerator/src/test/kotlin/DNAseqExample.kt
DifferenceGenerator/src/test/kotlin/DifferenceGeneratorTest.kt
DifferenceGenerator/src/test/kotlin/ReadRuntimeTests.kt
DifferenceGenerator/src/test/python/README.md
DifferenceGenerator/src/test/python/main.py

wrote a python script to call the jar with given parameters
to run get an executable jar
give the python script the jar path
wait for optuna to optimize
results are stored in the db

setup to optimize any algorithm with optuna

---

DifferenceGenerator/.gitignore
DifferenceGenerator/src/main/kotlin/DifferenceGenerator.kt
DifferenceGenerator/src/main/kotlin/algorithms/AlignmentAlgorithm.kt
DifferenceGenerator/src/main/kotlin/algorithms/DivideAndConquerAligner.kt
DifferenceGenerator/src/main/kotlin/algorithms/Gotoh.kt
DifferenceGenerator/src/main/kotlin/hashing/ObjectHasher.kt
DifferenceGenerator/src/main/kotlin/hashing/VideoFrameHasher.kt
DifferenceGenerator/src/main/kotlin/mask/CompositeMask.kt
DifferenceGenerator/src/main/kotlin/mask/Mask.kt
DifferenceGenerator/src/main/kotlin/mask/RectangularMask.kt
DifferenceGenerator/src/main/kotlin/metrics/PixelCountMetric.kt
DifferenceGenerator/src/main/kotlin/wrappers/IterableFrameGrabber.kt
DifferenceGenerator/src/main/kotlin/wrappers/MaskedImageGrabber.kt
DifferenceGenerator/src/main/kotlin/wrappers/Resettable2DFrameConverter.kt
DifferenceGenerator/src/main/kotlin/wrappers/ResettableArrayListIterator.kt
DifferenceGenerator/src/main/kotlin/wrappers/ResettableIterable.kt
DifferenceGenerator/src/test/kotlin/DNAseqExample.kt
DifferenceGenerator/src/test/kotlin/DifferenceGeneratorTest.kt
DifferenceGenerator/src/test/kotlin/ReadRuntimeTests.kt
DifferenceGenerator/src/test/kotlin/WriteRuntimeTests.kt
DifferenceGenerator/src/test/kotlin/metrics/PixelCountMetricTest.kt
DifferenceGenerator/src/test/python/main.py

find identical images:
- two images are identical if they have the same hash value
- we only consider image that appear only once in a single video

divide and conquer of Gotoh based on identical images

---

GUI/.gitignore
GUI/README.md
GUI/build.gradle.kts
GUI/src/main/kotlin/Main.kt
GUI/src/main/kotlin/SelectVideoScreen.kt
GUI/src/main/kotlin/VideoEdit.kt

test files can be find on the drive folder (GUI-.Screenshots).

feat(gui): display different resolutions of test images

---

GUI/src/main/kotlin/Main.kt
GUI/src/main/kotlin/VideoEdit.kt

feat(gui): basic functionalities of buttons and Keys

---

VideoGenerator/README.md
VideoGenerator/benchmarkOutput.txt
VideoGenerator/library/src/test/kotlin/VideoGeneratorBenchmarkTest.kt

also added the results from the benchmark Run

- refactor benchmark Test to work with same input datasets

---

.github/workflows/build.yml
.github/workflows/license.yml

Closes #146
Blocked by #164 
Needs to be rebased after merging license check, because the license checks otherwise fail

Extend CI pipeline

---

GUI/src/main/kotlin/frameNavigation/FrameNavigation.kt
GUI/src/main/kotlin/ui/components/FileSelectorButton.kt
GUI/src/main/kotlin/ui/screens/DiffScreen.kt

created function to save collage given a path added to menu list

---

GUI/src/main/kotlin/ui/components/AutoSizeText.kt
GUI/src/main/kotlin/ui/components/FileSelectorButton.kt
GUI/src/main/kotlin/ui/components/HelpDropDown.kt
GUI/src/main/kotlin/ui/screens/DiffScreen.kt
GUI/src/main/kotlin/ui/screens/SelectVideoScreen.kt

added menu bar for help and fixed text sizings

---

GUI/build.gradle.kts
GUI/src/main/kotlin/ui/components/FileSelectorButton.kt
GUI/src/main/kotlin/ui/components/ProjectManager.kt
GUI/src/main/kotlin/ui/screens/DiffScreen.kt
GUI/src/main/kotlin/ui/screens/Screen.kt
GUI/src/main/kotlin/ui/screens/SelectVideoScreen.kt

added json serialization of the state
closes #159

create project import and export using json

---

.github/workflows/test.yml
GUI/README.md
GUI/build.gradle.kts
GUI/src/test/kotlin/ui/SelectVideoScreenTest.kt
licenses/allowed-licenses.json

Test(GUI): Adding ui tests and CI integration.

---

GUI/src/main/kotlin/frameNavigation/FrameNavigation.kt
GUI/src/main/kotlin/models/AppState.kt
GUI/src/main/kotlin/ui/components/diffScreen/ImageDisplayer.kt
GUI/src/main/kotlin/ui/components/diffScreen/SaveCollageButton.kt
GUI/src/main/kotlin/ui/components/general/FileSelector.kt
GUI/src/main/kotlin/ui/components/general/ProjectManager.kt
GUI/src/main/kotlin/ui/components/general/SaveableImage.kt
GUI/src/main/kotlin/ui/components/selectVideoScreen/FileSelectorButton.kt
GUI/src/main/kotlin/ui/screens/DiffScreen.kt
GUI/src/main/kotlin/ui/screens/SelectVideoScreen.kt
GUI/src/main/kotlin/ui/screens/SettingsScreen.kt

Feat(GUI): Make FilePickers remember last used folder.

---

DifferenceGenerator/src/main/kotlin/DifferenceGenerator.kt
DifferenceGenerator/src/main/kotlin/Exceptions.kt
DifferenceGenerator/src/main/kotlin/mask/CompositeMask.kt
DifferenceGenerator/src/test/kotlin/DifferenceGeneratorTest.kt
GUI/src/main/kotlin/frameNavigation/FrameNavigation.kt
GUI/src/main/kotlin/frameNavigation/FrameNavigationInterface.kt
GUI/src/main/kotlin/logic/differenceGeneratorWrapper/DifferenceGeneratorWrapper.kt
GUI/src/main/kotlin/ui/components/diffScreen/Timeline.kt
GUI/src/main/kotlin/ui/components/general/ErrorDialog.kt
GUI/src/main/kotlin/ui/components/selectVideoScreen/ComputeDifferencesButton.kt

feat(gui): error handling to prevent program crashes

---

GUI/src/main/kotlin/Main.kt
GUI/src/main/kotlin/frameNavigation/FrameNavigation.kt
GUI/src/main/kotlin/models/AppState.kt
GUI/src/main/kotlin/ui/screens/DiffScreen.kt

added cleanup

---

GUI/src/main/kotlin/logic/GetVideoMetadata.kt
GUI/src/main/kotlin/ui/components/general/ProjectManager.kt
GUI/src/main/kotlin/ui/components/selectVideoScreen/ComputeDifferencesButton.kt

added metadata to the video file and errorhandling

---

GUI/src/main/kotlin/ui/components/diffScreen/Timeline.kt

small fix for difference colors

added colors for non-perfect matches, color subject to change

---

GUI/src/main/kotlin/ui/components/selectVideoScreen/ComputeDifferencesButton.kt
GUI/src/main/kotlin/ui/screens/SelectVideoScreen.kt

This was removed by accident in commit 30d196a3 during a rebase.

fix(gui): add confirmation popup back on computation

---

DifferenceGenerator/build.gradle.kts
GUI/build.gradle.kts
GUI/src/main/kotlin/Main.kt
VideoGenerator/build.gradle.kts

In this PR, the version numbers are incremented by one.
Important for the RM. :)

Prepare next release

---

DifferenceGenerator/src/main/kotlin/DifferenceGenerator.kt
DifferenceGenerator/src/main/kotlin/util/ColorEncoding.kt
DifferenceGenerator/src/main/kotlin/util/ColoredFrameGenerator.kt
GUI/src/main/kotlin/frameNavigation/FrameNavigation.kt
GUI/src/main/kotlin/ui/components/diffScreen/timeline/OverviewBar.kt
GUI/src/main/kotlin/ui/components/diffScreen/timeline/PositionIndicator.kt
GUI/src/main/kotlin/ui/components/diffScreen/timeline/StatisticalInformation.kt
GUI/src/main/kotlin/ui/components/diffScreen/timeline/Timeline.kt
GUI/src/main/kotlin/ui/components/general/InfoIconWithHover.kt
GUI/src/main/kotlin/ui/components/general/TitleWithInfo.kt
GUI/src/main/kotlin/ui/components/general/Tooltip.kt

To red for deletion, yellow for pixel differences, green for insertion.

feat(general): change diff color encoding

---

GUI/src/main/kotlin/Main.kt
GUI/src/main/kotlin/models/AppState.kt
GUI/src/main/kotlin/ui/components/general/CheckIfSavedDialog.kt
GUI/src/main/kotlin/ui/components/general/ProjectManager.kt
GUI/src/main/kotlin/ui/components/selectVideoScreen/ComputeDifferencesButton.kt
GUI/src/main/kotlin/ui/components/settingsScreen/SaveButton.kt
GUI/src/main/kotlin/ui/screens/DiffScreen.kt
GUI/src/main/kotlin/ui/screens/SettingsScreen.kt

closes #254 
Works on Windows (@akriese ) but on Mac, Project loading and saving is unstable. The metadata seam to disappear unpredictably. Thus, projects can be saved but can often not be loaded after some minutes. This is the case on the current main branch as well, so not introduced by this PR.

Feature(GUI): Warn user if settings or computations are about to be lost.

---

DifferenceGenerator/build.gradle.kts
GUI/build.gradle.kts

This reverts commit dd679f11475330580c429af915406d5ebb92df55.

fix(gui): missing dependency

---

GUI/src/main/kotlin/ui/screens/DiffScreen.kt

Fix(GUI): Fix freezing after backbutton confirm dialog on DiffScreen.

---

GUI/src/main/kotlin/ui/components/general/AutoSizeText.kt
GUI/src/main/kotlin/ui/components/selectVideoScreen/FileSelectorButton.kt

Feat(GUI): Change upload button size
