DifferenceGenerator/build.gradle.kts, DifferenceGenerator/src/main/kotlin/AbstractDifferenceGenerator.kt, DifferenceGenerator/src/main/kotlin/AcceptedCodecs.kt, DifferenceGenerator/src/main/kotlin/DifferenceGenerator.kt, DifferenceGenerator/src/main/kotlin/Main.kt
Closes #6 
This PR adds a non abstract implementation of the AbstractDifferenceGenerator. 
It only implements the initialiser which is supposed to check wether the input files are encoded lossless.
This already required a comprehensive library, I used javaCV because it can be imported only by adding it to the `gradle.build.kts` file and nothing has to be installed manually.
I hardcoded accepted video codecs as a globally accessible object. The list of codecs is not yet fully evaluated and can be edited after further discussing with _esolutions_. I think it makes sense to agree to a couple of codecs and enforce them.
=> Add initialiser for lib2 

DifferenceGenerator/src/main/kotlin/DifferenceGenerator.kt, DifferenceGenerator/src/main/kotlin/Resettable2DFrameConverter.kt
extends the Java2DFrameConverter to reset its internal state after a conversion, so that the instance can be reused without side effects.
This is not closing any ticket, rather came up in several discussions (#42, #69)
=> feat(lib2): resettable frame converter

VideoGenerator/example/app/src/main/java/de/guiframediff/videogeneratorexample/MainActivity.kt, VideoGenerator/library/.gitignore, VideoGenerator/library/src/main/kotlin/AbstractVideoGenerator.kt, VideoGenerator/library/src/main/kotlin/VideoGeneratorImpl.kt, VideoGenerator/library/src/main/kotlin/VideoGeneratorImplTests.kt
Until now, the image size was given explicitly to the videogenarator. I think this is unnecessary and also leads to typos and thus to distorted images (if the ratio does not match).
=> fix(lib1): Determine image size from first frame and not pass it explicitly in the constructor.

.gitignore, DifferenceGenerator/build.gradle.kts, GUI/build.gradle.kts, README.md, licenses/allowed-licenses.json
This uses the gradle plugin available at https://github.com/jk1/Gradle-License-Report. So far only tested for lib2 (DifferenceGenerator).
I will open this for merge, when the plugin can be applied to the other two subprojects
=> feat(license): use gradle plugin to perform license check

DifferenceGenerator/src/test/kotlin/ReadRuntimeTests.kt, DifferenceGenerator/src/test/kotlin/WriteRuntimeTests.kt
reading a frame is optimal for bytearray with single loop:
same goes for writing to a frame:
Confirm this decision for refactoring the DifferenceGeneratorClass
=> tests for reading a frame and writing a frame

VideoGenerator/library/src/main/kotlin/VideoGeneratorBenchmarkTest.kt, VideoGenerator/library/src/main/kotlin/VideoGeneratorImpl.kt, VideoGenerator/library/src/main/kotlin/VideoGeneratorStressTest.kt
```
Codec: ffv1
Loading 10 Files took 1241 ms (124 ms / frame)
File size reduced from 2.3 MB to 1.9 MB (83.3%)
Codec: ffv1
Loading 100 Files took 6059 ms (60 ms / frame)
File size reduced from 23.6 MB to 18.3 MB (77.6%)
Codec: ffv1
Loading 500 Files took 29272 ms (58 ms / frame)
File size reduced from 113.2 MB to 86.1 MB (76.1%)
Codec: ffv1
Loading 800 Files took 45525 ms (56 ms / frame)
File size reduced from 173.3 MB to 133.4 MB (77.0%)
Codec: ffv1
Loading 1000 Files took 58758 ms (58 ms / frame)
File size reduced from 220.6 MB to 169.7 MB (76.9%)
Codec: vp9
Loading 10 Files took 1804 ms (180 ms / frame)
File size reduced from 2.7 MB to 1.5 MB (54.2%)
Codec: vp9
Loading 100 Files took 17195 ms (171 ms / frame)
File size reduced from 24 MB to 13.7 MB (57.1%)
Codec: vp9
Loading 500 Files …
```
=> Lib1 performance comparison tests with different codecs

.editorconfig, .github/workflows/lint.yml, .github/workflows/test.yml, DifferenceGenerator/build.gradle.kts, DifferenceGenerator/src/main/kotlin/DifferenceGenerator.kt, DifferenceGenerator/src/test/kotlin/ReadRuntimeTests.kt, DifferenceGenerator/src/test/kotlin/WriteRuntimeTests.kt, VideoGenerator/library/build.gradle.kts, VideoGenerator/library/src/main/kotlin/VideoGeneratorBenchmarkTest.kt, VideoGenerator/library/src/main/kotlin/VideoGeneratorImpl.kt
This enables CI linting (ktlint v1.0.1) and testing (lib1 unit tests, lib2). The gradle caches are cached by the `setup-java` action to speed up repeated runs.
There are some side effects to this PR: 
- FFmpeg logging was turned of in the `DifferenceGenerator` and `VideoGenerator` classes to reduce the cluttering logging output.
- Our various benchmark tests were tagged with the `"benchmark"` tag and that tag was excluded in the `build.gradle.kts` files to reduce the running time of `gradle test`
- The `.editorconfig` was modified to contain the project `root` key. Also, some more explicit settings were added, which does not effectively change the previous implicit settings (AFAIK at least)
The tests currently run in 2 minutes for each library if cached (longer if not cached).
See below …
=> ci: init lint and test workflows

DifferenceGenerator/build.gradle.kts, GUI/build.gradle.kts, README.md, VideoGenerator/build.gradle.kts, licenses/README.md, licenses/allowed-licenses.json
This is done by including certain packages in the
allowed licenses file. The plugin has trouble with resolving license files for the mentioned packages, which is mentioned in the new license README with a link to the issue on GitHub.
I checked the mentioned packages (all jetbrains') and they all offer the Apache 2.0 license, so this should be fine.
=> doc(general): fix license checks

DifferenceGenerator/src/test/kotlin/TestCaseGenerator.kt
The testCaseGenerator now works with all four possible AlignmentElements (Insertion, Deletion, Match and Perfect).
closes #144
=> fix(lib2): Adjust the TestCaseGenerator to the new AlignmentElement

GUI/src/main/kotlin/ui/components/DifferenceImageDisplayer.kt
selected 15 percent for buttons, because 8% was too small:
8%:
15%
=> Changed Button proportions

GUI/build.gradle.kts, GUI/src/main/kotlin/Main.kt
I tried using a plugin (https://github.com/gmazzo/gradle-buildconfig-plugin) to not having to have the version numbers in different places, but I couldnt get it to work. 
So this is the simplest approach, but one has to change the version number in AppConfig aswell as in the gradle script.
This closes part 2 of #171
=> feat(gui): display version number in window title

GUI/build.gradle.kts, GUI/src/main/kotlin/ui/components/CustomSlider.kt, GUI/src/main/kotlin/ui/components/FileSelectorButton.kt, GUI/src/main/kotlin/ui/components/InfoIconWithHover.kt, GUI/src/main/kotlin/ui/components/TextTitle.kt, GUI/src/main/kotlin/ui/components/TitleWithInfo.kt, GUI/src/main/kotlin/ui/components/Tooltip.kt, GUI/src/main/kotlin/ui/screens/SettingsScreen.kt
Closes #172 
This PR adds info icons in the settings screen. When hovering the icons, a corresponding text is displayed.
=> Add info icons

DifferenceGenerator/src/main/kotlin/DifferenceGenerator.kt, DifferenceGenerator/src/main/kotlin/util/ColoredFrameGenerator.kt, GUI/src/main/kotlin/frameNavigation/FrameNavigation.kt, GUI/src/main/kotlin/frameNavigation/FrameNavigationInterface.kt, GUI/src/main/kotlin/ui/components/diffScreen/Timeline.kt
=> feat(gui): time line with thumbnail preview and scrollbar

DifferenceGenerator/src/main/kotlin/AbstractDifferenceGenerator.kt, DifferenceGenerator/src/main/kotlin/DifferenceGenerator.kt, DifferenceGenerator/src/test/kotlin/DifferenceGeneratorTest.kt, DifferenceGenerator/src/test/kotlin/ReadRuntimeTests.kt, GUI/src/main/kotlin/frameNavigation/FrameNavigation.kt, GUI/src/main/kotlin/logic/differenceGeneratorWrapper/DifferenceGeneratorWrapper.kt, GUI/src/main/kotlin/models/AppState.kt, GUI/src/main/kotlin/ui/components/diffScreen/StatisticalInformation.kt, GUI/src/main/kotlin/ui/components/selectVideoScreen/ComputeDifferencesButton.kt, GUI/src/main/kotlin/ui/components/selectVideoScreen/FileSelectorButton.kt, GUI/src/main/kotlin/ui/screens/DiffScreen.kt, GUI/src/main/kotlin/ui/screens/SelectVideoScreen.kt, GUI/src/test/kotlin/ui/SelectVideoScreenTest.kt
Closes #219.
Due to the POs wanting the name "current" for the second video, I chose to name many of the variables 
videoReference/videoCurrent instead of referenceVideo/currentVideo to avoid confusion with variables like currentIndex (e.g. FrameNavigation)
=> refactor: rename video1/2 to reference/current

GUI/src/main/kotlin/frameNavigation/FrameNavigation.kt, GUI/src/main/kotlin/logic/caches/ThumbnailCache.kt, GUI/src/main/kotlin/ui/components/diffScreen/NavigationRow.kt, GUI/src/main/kotlin/ui/components/diffScreen/Timeline.kt, GUI/src/main/kotlin/ui/components/general/SvgButton.kt
This is not connected to any ticket, but was briefly mentioned in our team meeting.
I did a little refactor of the ThumbnailCache on the side :)
=> feat(gui): disable the navigation buttons if their actions are not possible

GUI/src/main/kotlin/ui/components/diffScreen/Timeline.kt
This was caused on machines that had a different pixel density than 1.0, which needed to be accounted for weirdly.
@AlperK61 @simonsasse, I know, both of you had this issue on at least on screen. Can you try the fix? :)
=> fix(gui): weird timeline label offset on some PCs

DifferenceGenerator/build.gradle.kts, GUI/build.gradle.kts, GUI/src/main/kotlin/Main.kt, VideoGenerator/build.gradle.kts
I changed the version number based on @akriese's proposal to the number of the now ending sprint.
Should be merged last before releasing.
=> Set new version number based on sprint number

DifferenceGenerator/src/main/kotlin/DifferenceGenerator.kt, DifferenceGenerator/src/main/kotlin/Exceptions.kt, DifferenceGenerator/src/main/kotlin/algorithms/AlignmentAlgorithm.kt, DifferenceGenerator/src/main/kotlin/algorithms/DivideAndConquerAligner.kt, GUI/src/main/kotlin/ui/components/selectVideoScreen/ComputeDifferencesButton.kt, GUI/src/main/kotlin/ui/components/selectVideoScreen/LoadingDialog.kt, GUI/src/main/kotlin/ui/screens/SelectVideoScreen.kt
=> loading spinner

GUI/README.md, GUI/src/main/kotlin/Main.kt, GUI/src/main/kotlin/logic/differenceGeneratorWrapper/DifferenceGeneratorWrapper.kt, GUI/src/main/kotlin/models/AppState.kt, GUI/src/main/kotlin/ui/components/selectVideoScreen/ComputeDifferencesButton.kt, GUI/src/main/kotlin/ui/components/selectVideoScreen/FileSelectorButton.kt, GUI/src/main/kotlin/ui/screens/SettingsScreen.kt
This makes app state paths nullable and introduces an env variable `GUI_USE_DEFAULT_PATHS` that can be set to use some default paths for convenience. Read more in [`./GUI/README.md`](https://github.com/amosproj/amos2023ws03-gui-frame-diff/tree/gui/feature/nullable-paths/GUI#readme)
=> feat(gui): nullable paths

GUI/src/main/kotlin/ui/screens/SettingsScreen.kt
=> delete mask button

GUI/src/main/kotlin/ui/screens/SelectVideoScreen.kt
If for either input video no path is set, the file picker will launch in the directory of the other input file. This assumes, that both video are somewhat close to each other.
=> feat(gui): video selector default dir connected

DifferenceGenerator/src/main/kotlin/AcceptedCodecs.kt, DifferenceGenerator/src/main/kotlin/DifferenceGenerator.kt, DifferenceGenerator/src/main/kotlin/Exceptions.kt, DifferenceGenerator/src/main/kotlin/mask/CompositeMask.kt, GUI/src/main/kotlin/ui/components/selectVideoScreen/ComputeDifferencesButton.kt
Pass video and mask dimensions, and the used and allowed codecs whenever an exception is thrown.
Tackles part of #269
=> feat: more information in exceptions

DifferenceGenerator/src/main/kotlin/algorithms/DivideAndConquerAligner.kt, DifferenceGenerator/src/main/kotlin/wrappers/Resettable2DFrameConverter.kt
remove both duplicates while hashing
barely anything changed but finding the bug and correct place for placing the .gc() took way too long
=> added Garbage Collection Call

DifferenceGenerator/src/main/kotlin/util/ColoredFrameGenerator.kt
reuse Frames when recording: imporoves Runtime by 6%
=> Optimizations

GUI/src/main/kotlin/ui/components/general/Tooltip.kt
This would previously only work nicely on screens without scaling (windows: 100%). As the many localdensity issues we had before...
=> fix(gui): tooltip offset depending on density

GUI/src/main/kotlin/ui/components/diffScreen/timeline/OverviewBar.kt
This was a bug that came with the assumption that all colored boxed in the OverviewBar get the same width in pixels, which is not true. This issue becomes only clear with long diff sequences as some boxes seem much bigger than others (at most 1 pixel wider). We keep the boxes sizes, but save their offset in the row to determine which box was actually clicked.
This is needed for the cursor drag feature as otherwise we could simply give each box its own tapGesture event handler.
=> fix(gui): jump to the correct frame on OverviewBar click
